### ISSUE TITLE
Doesn't work on windows 10

### ISSUE THREAD

**Issue by pepperminting** [aigc-apps/EasyPhoto#11]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ai\.conda\envs\easyphoto\Lib\site-packages\accelerate\commands\launch.py", line 933, in <module>
    main()
  File "C:\Users\Ai\.conda\envs\easyphoto\Lib\site-packages\accelerate\commands\launch.py", line 929, in main
    launch_command(args)
  File "C:\Users\Ai\.conda\envs\easyphoto\Lib\site-packages\accelerate\commands\launch.py", line 900, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ai\.conda\envs\easyphoto\Lib\site-packages\accelerate\commands\launch.py", line 781, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ai\.conda\envs\easyphoto\Lib\site-packages\accelerate\commands\config\config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ai\.conda\envs\easyphoto\Lib\site-packages\accelerate\commands\config\config_args.py", line 133, in from_yaml_file
    return cls(**config_dict)
           ^^^^^^^^^^^^^^^^^^
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
Error executing the command: Command '['C:\\Users\\Ai\\.conda\\envs\\easyphoto\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'C:\\Users\\Ai\\Developers\\StableDiffusion\\EasyPhoto\\easyphoto\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=model_data\\Others\\stable-diffusion-v1-5', '--pretrained_model_ckpt=model_data\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\oh\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\oh\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\oh\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=model_data\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=oh', '--cache_log_file=./model_data\\train_kohya_log.txt', '--validation']' returned non-zero exit status 1.
```
This code doesn't work on Windows.

**Comment by guxin001** [comment]
初始化环境一堆报错，开源真是心累

**Comment by longglecc** [comment]
windows is fine， but linux does not work.
