### ISSUE TITLE
Train error. cant start.

### ISSUE THREAD

**Issue by farizy4n** [aigc-apps/EasyPhoto#15]
train_file_path :  E:\Ai\TensorRT\webui\extensions\sd-webui-EasyPhoto\scripts\train_kohya/train_lora.py
cache_log_file_path: E:\Ai\TensorRT\webui\outputs/easyphoto-tmp/train_kohya_log.txt
bin E:\Ai\TensorRT\webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Traceback (most recent call last):
  File "C:\Users\Al Farizy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Al Farizy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Ai\TensorRT\webui\venv\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "E:\Ai\TensorRT\webui\venv\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "E:\Ai\TensorRT\webui\venv\lib\site-packages\accelerate\commands\launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "E:\Ai\TensorRT\webui\venv\lib\site-packages\accelerate\commands\launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "E:\Ai\TensorRT\webui\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "E:\Ai\TensorRT\webui\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
Error executing the command: Command '['E:\\Ai\\TensorRT\\webui\\venv\\Scripts\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'E:\\Ai\\TensorRT\\webui\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\v1-5-pruned.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\ohxviona\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=1500', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\ohxviona\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\ohxviona\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=ohxviona', '--cache_log_file=E:\\Ai\\TensorRT\\webui\\outputs/easyphoto-tmp/train_kohya_log.txt', '--validation']' returned non-zero exit status 1.
Using already loaded model Best of the best\mikasmix_v10.ckpt [951cbe16c9]: done in 0.8s (send model to device: 0.8s

**Comment by longglecc** [comment]
me too
